### ISSUE TITLE
Is this meant as a collective Open Source collection?

### ISSUE THREAD

**Issue by timmwille** [ceremcem/freecad-notes#9]
Hi @ceremcem!

I just stumbled upon this and find it amazing, so many people working on the dev of FreeCAD now, so some notes on missing Documentation especially also when it comes to the extend of the realthunder Features to be documented, tested, hopefully integrated.

Just let me know what you think, I also found some forum entries of yours very helpful, will try to use it as well a bit more now, but compared to work with Issues, it seems a monster :D 

Why asking this: I want to find a good entry point to help with the tips and tricks around FreeCAD that might lead to less frustration and straight forward solutions (eventually end up in the wiki) while on-boarding a bunch of engineers now to FreeCAD (Open Source Hardware developer). :) 

My current Setup:
Manjaro Linux (Arch)
[FreeCAD-LinkStage3-AUR-Build](https://aur.archlinux.org/packages/freecad-linkstage3-git)
Next Challenge: get asm3 finally to work and write some Guidance around it, that is currently scattered around in GitHub, Forum and Wiki (slvs for python >3.9 working?)

Feel absolutely free to point me at any better direction to join forces (in the forum I feel a bit lost, so I ended up here).

PS:
I was wondering if you could add an MIT or CC-BY License (or any open source version) to this repo?, I can also send you a Pull Request if it helps. From your Issues I understood some help and collaboration is wanted? (I was planning on opening a similar notes repository, but would rather join in my info here)

**Comment by timmwille** [comment]
interesting approach:
https://github.com/ceremcem/build-freecad-asm3

for some might work but if I see myself struggle, I know for others it will be too time consuming if they just want to test an Add-On or work with it (even if it has some bugs) on some hardware projects. So is there an easier way to automate this a bit?

**Comment by ceremcem** [comment]
Hi, 

I'm glad if I could help. 

> From your Issues I understood some help and collaboration is wanted?

Correct. I've started this HOWTO as a "cheatsheet of FreeCAD", so anyone would benefit. As for license: MIT fits this case, I suppose. 

> So is there an easier way to automate this a bit?

Those steps should be manually performed in order to benefit from all advantages of using an LXC container. In other words, "you should know what you are doing".  

Maybe a Docker image would make everything easier. I couldn't use it yet but realthunder provides something like that: https://github.com/realthunder/FreeCADMakeImage

I don't fully understand how to build Docker images yet but it may worth to learn for this purpose.

**Comment by timmwille** [comment]
thx, please check out my fix with PR #10
